# 7-base_geometry.py

This module defines a class BaseGeometry
``base = BaseGeometry()``

## Usage:
``base = BaseGeometry()`` create a BaseGeometry object

::
    >>> BaseGeometry = __import__("7-base_geometry").BaseGeometry
    >>> base = BaseGeometry()

::
    >>> base.integer_validator("value1", 10)
    >>> base.integer_validator("value2", 1)


## Invalidations:

BaseGeometry doesn't have __init__ function and no takes arguments

::
    >>> BaseGeometry(213)
    Traceback (most recent call last):
    TypeError: BaseGeometry() takes no arguments

area method is not implemented yet

::
    >>> base.area()
    Traceback (most recent call last):
    Exception: area() is not implemented

area method doesn't receiving parameters

::
    >>> base.area(47)
    Traceback (most recent call last):
    TypeError: area() takes 1 positional argument but 2 were given

integer_validator method requires value parameter

    >>> base.integer_validator("name")
    Traceback (most recent call last):
    TypeError: integer_validator() missing 1 required positional argument: 'value'

integer_validator method requires value and name parameters in the same time

    >>> base.integer_validator()
    Traceback (most recent call last):
    TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

integer_validator method requires just value and name parameters in the same time no more

    >>> base.integer_validator("name", 213, 47)
    Traceback (most recent call last):
    TypeError: integer_validator() takes 3 positional arguments but 4 were given

integer_validator method accept just int value

::
    >>> base.integer_validator("name", "Abdo")
    Traceback (most recent call last):
    TypeError: name must be an integer

integer_validator method accept just the integers that greater then 0

::
    >>> base.integer_validator("num", 0)
    Traceback (most recent call last):
    ValueError: num must be greater than 0

::
    >>> base.integer_validator("num", -47)
    Traceback (most recent call last):
    ValueError: num must be greater than 0
